namespace Si.IdCheck.ApiClients.CloudCheck.Constants;
public static class CloudCheckRelationshipConsts
{
    public const string Wife = "WIFE";
    public const string Husband = "HUSBAND";
    public const string Brother = "BROTHER";
    public const string Sister = "SISTER";
    public const string Son = "SON";
    public const string Daughter = "DAUGHTER";
    public const string Mother = "MOTHER";
    public const string Father = "FATHER";
    public const string Cousin = "COUSIN";
    public const string Stepson = "STEP-SON";
    public const string Stepdaughter = "STEP-DAUGHTER";
    public const string BrotherInLaw = "BROTHER-IN LAW";
    public const string SisterInLaw = "SISTER-IN-LAW";
    public const string Uncle = "UNCLE";
    public const string Aunt = "AUNT";
    public const string MotherInLaw = "MOTHER-IN-LAW";
    public const string FatherInLaw = "FATHER-IN-LAW";
    public const string Grandfather = "GRANDFATHER";
    public const string Grandmother = "GRANDMOTHER";
    public const string SonInLaw = "SON-IN-LAW";
    public const string DaughterInLaw = "DAUGHTER-IN-LAW";
    public const string Niece = "NIECE";
    public const string Nephew = "NEPHEW";
    public const string Grandson = "GRANDSON";
    public const string GrandDaughter = "GRANDDAUGHTER";
    public const string StepFather = "STEPFATHER";
    public const string StepMother = "STEPMOTHER";
    public const string BusinessAssociate = "BUSINESS ASSOCIATE";
    public const string Friend = "FRIEND";
    public const string FinancialAdviser = "FINANCIAL ADVISER";
    public const string LegalAdviser = "LEGAL ADVISER";
    public const string Colleague = "COLLEAGUE";
    public const string AgentRepresentative = "AGENT/REPRESENTATIVE";
    public const string Employee = "EMPLOYEE";
    public const string Associate = "ASSOCIATE";
    public const string Child = "CHILD";
    public const string FamilyMember = "FAMILY MEMBER";
    public const string PoliticalAdviser = "POLITICAL ADVISER";
    public const string SeniorOfficial = "SENIOR OFFICIAL";
    public const string UnmarriedPartner = "UNMARRIED PARTNER";
    public const string SameSexSpouse = "SAME-SEX SPOUSE";
    public const string Employer = "EMPLOYER";
}
